// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simcag.PriceAnalysisService.Infrastructure.Persistence.DbContext;

#nullable disable

namespace Simcag.PriceAnalysisService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PriceAnalysisDbContext))]
    partial class PriceAnalysisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simcag.PriceAnalysisService.Domain.Entities.PriceAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnalysisNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("DeviationPercentage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("HistoricalAverage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAnomalous")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MarketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDate");

                    b.HasIndex("IsAnomalous");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
